[config]
schemaVersion = "0.0.1"

[package]
namespace = "Mythic"
name = "SOTF_Autosave"
versionNumber = "0.1.0"
description = "Performs an autosave over a configurable interval, once every 5 minutes by default"
websiteUrl = "https://github.com/MythicManiac/SonsOfTheForest"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_IL2CPP = "6.0.667"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./ReleaseOutput"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["sons-of-the-forest"]
categories = []
